"""Add relevance_score and k_value to Account model

Revision ID: 207693e32403
Revises: 25e8380620d4
Create Date: 2024-10-03 10:06:06.111486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '207693e32403'
down_revision: Union[str, None] = '25e8380620d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('relevance_score', sa.Float(), nullable=True))
    op.add_column('account', sa.Column('k_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'k_value')
    op.drop_column('account', 'relevance_score')
    # ### end Alembic commands ###
