"""add already_processed_to_source_data to sourcefile model

Revision ID: 25e8380620d4
Revises: ad77f9e4d6e4
Create Date: 2024-10-01 17:35:52.362558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '25e8380620d4'
down_revision: Union[str, None] = 'ad77f9e4d6e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sourcefile', sa.Column('already_processed_to_source_data', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sourcefile', 'already_processed_to_source_data')
    # ### end Alembic commands ###
