"""sort double id issue

Revision ID: 2688e2564b5a
Revises: 857d5dd65127
Create Date: 2025-09-20 14:04:22.572752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2688e2564b5a'
down_revision: Union[str, None] = '857d5dd65127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scorecardresult')
    op.drop_table('scoreapp_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoreapp_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scoreapp_id', sa.VARCHAR(), nullable=False),
    sa.Column('account_unique_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['account_unique_id'], ['account.account_unique_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scorecardresult',
    sa.Column('result_id', sa.TEXT(), nullable=False),
    sa.Column('account_unique_id', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('first_name', sa.TEXT(), nullable=True),
    sa.Column('last_name', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('key', sa.TEXT(), nullable=False),
    sa.Column('report_url', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['account_unique_id'], ['account.account_unique_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    # ### end Alembic commands ###
