"""create widgetconfig table

Revision ID: 2cc0b1f0e4a4
Revises: e0cf51caf684
Create Date: 2025-09-16 08:34:16.877169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2cc0b1f0e4a4'
down_revision: Union[str, None] = 'e0cf51caf684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widgetconfig',
    sa.Column('account_unique_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('theme_colour', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('button_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('widget_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('welcome_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('opt_in_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_unique_id'], ['account.account_unique_id'], ),
    sa.ForeignKeyConstraint(['widget_id'], ['widgetapikey.id'], ),
    sa.PrimaryKeyConstraint('widget_id')
    )
    with op.batch_alter_table('widgetconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_widgetconfig_account_unique_id'), ['account_unique_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('widgetconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widgetconfig_account_unique_id'))

    op.drop_table('widgetconfig')
    # ### end Alembic commands ###
