"""bfa-257 add product title to subs

Revision ID: 4f91bc715657
Revises: d1c15cc3fcaf
Create Date: 2025-06-18 08:01:57.623607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4f91bc715657'
down_revision: Union[str, None] = 'd1c15cc3fcaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('product_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('product_statement_descriptor',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_product_product_id'), ['product_id'], unique=True)

    with op.batch_alter_table('stripesubscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_product_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripesubscription', schema=None) as batch_op:
        batch_op.drop_column('related_product_title')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_product_id'))
        batch_op.alter_column('product_statement_descriptor',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('product_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
