"""bfa-229 Add product model

Revision ID: 599fc27c3217
Revises: 908b3b49e14d
Create Date: 2025-06-13 10:53:43.857360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '599fc27c3217'
down_revision: Union[str, None] = '908b3b49e14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.String(length=255), nullable=False, primary_key=True),
        sa.Column("product_title", sa.String(length=255), nullable=False),
        sa.Column("product_description", sa.String(length=255), nullable=True),
        sa.Column("product_price", sa.Float(), nullable=False),
        sa.Column("product_plan_cycle", sa.String(length=255), nullable=False),
        sa.Column("product_statement_descriptor", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    # ### end Alembic commands ###
