"""bfa-229 rename product table

Revision ID: 60422a85b48f
Revises: 599fc27c3217
Create Date: 2025-06-13 11:30:24.687364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60422a85b48f'
down_revision: Union[str, None] = '599fc27c3217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('products', 'product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('product', 'products')
    # ### end Alembic commands ###
