"""bfa-211 Add stripe subscription model

Revision ID: 6a0c70ab3dc1
Revises: a49b82230b8f
Create Date: 2025-06-12 11:40:13.979793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a0c70ab3dc1'
down_revision: Union[str, None] = 'a49b82230b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripesubscription',
    sa.Column('account_unique_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('subscription_start', sa.DateTime(), nullable=True),
    sa.Column('stripe_account_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['account_unique_id'], ['account.account_unique_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stripesubscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stripesubscription_stripe_account_url'), ['stripe_account_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_stripesubscription_stripe_customer_id'), ['stripe_customer_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_stripesubscription_stripe_subscription_id'), ['stripe_subscription_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_stripesubscription_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripesubscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stripesubscription_type'))
        batch_op.drop_index(batch_op.f('ix_stripesubscription_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_stripesubscription_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_stripesubscription_stripe_account_url'))

    op.drop_table('stripesubscription')
    # ### end Alembic commands ###
