"""Adding folder model for file storing

Revision ID: 739a0a2e8209
Revises: 8eab902251f0
Create Date: 2024-10-17 08:12:49.550690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '739a0a2e8209'
down_revision: Union[str, None] = '8eab902251f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sourcefile', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sourcefile', 'folder', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sourcefile', type_='foreignkey')
    op.drop_column('sourcefile', 'folder_id')
    # ### end Alembic commands ###