"""Adding folder model for file storing

Revision ID: 739a0a2e8209
Revises: 8eab902251f0
Create Date: 2024-10-17 08:12:49.550690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Keep if any sqlmodel specific types were used, though not apparent here


# revision identifiers, used by Alembic.
revision: str = '739a0a2e8209'
down_revision: Union[str, None] = '8eab902251f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sourcefile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            op.f('fk_sourcefile_folder_id_folder'), # Generated or explicit FK name
            'folder',                               # Target table for the FK
            ['folder_id'],                          # Column(s) in 'sourcefile'
            ['id']                                  # Column(s) in 'folder'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sourcefile', schema=None) as batch_op:
        batch_op.drop_constraint(
            op.f('fk_sourcefile_folder_id_folder'), # Use the same FK name as in upgrade
            type_='foreignkey'
        )
        batch_op.drop_column('folder_id')
    # ### end Alembic commands ###