"""Adding folder model for file storing

Revision ID: 74b5eda89cb1
Revises: b80969842197
Create Date: 2024-10-17 08:00:27.133244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '74b5eda89cb1'
down_revision: Union[str, None] = 'b80969842197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_unique_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['account_unique_id'], ['account.account_unique_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folder')
    # ### end Alembic commands ###
