"""bfa-245 add price_id to product model

Revision ID: 7dc4d2a01a06
Revises: 4c6381871e58
Create Date: 2025-06-16 08:31:56.225334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7dc4d2a01a06'
down_revision: Union[str, None] = '4c6381871e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_id', sa.VARCHAR(length=255), nullable=True, unique=True, index=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('price_id')
    # ### end Alembic commands ###
