"""bfa-229 Add product model

Revision ID: 908b3b49e14d
Revises: 6a0c70ab3dc1
Create Date: 2025-06-13 10:45:12.763245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '908b3b49e14d'
down_revision: Union[str, None] = '6a0c70ab3dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
