"""bfa-497 add source_files to ChatMessage table

Revision ID: 9710743376dc
Revises: 663cca6ccf12
Create Date: 2025-07-03 11:34:48.065103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9710743376dc'
down_revision: Union[str, None] = '663cca6ccf12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_files', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.drop_column('source_files')

    # ### end Alembic commands ###
