"""bfa-181 remove default uuid generator on visitor-uuid

Revision ID: a49b82230b8f
Revises: 2443ce9f61bb
Create Date: 2025-06-09 13:22:16.161776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a49b82230b8f'
down_revision: Union[str, None] = '2443ce9f61bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatsession_visitor_uuid'), ['visitor_uuid'], unique=False)
        batch_op.drop_column('account')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_chatsession_visitor_uuid'))

    # ### end Alembic commands ###
