"""bfa-410 add fields for lambda file processing

Revision ID: b8a04845dbf9
Revises: 1e2771a7325c
Create Date: 2025-06-26 12:40:37.430476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8a04845dbf9'
down_revision: Union[str, None] = '1e2771a7325c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    with op.batch_alter_table('sourcefile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('processing_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sourcefile', schema=None) as batch_op:
        batch_op.drop_column('processing_error')
        batch_op.drop_column('processing_status')
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
