"""add sentiment fields to chatsession

Revision ID: bb8ab4948953
Revises: f1f66de3266e
Create Date: 2026-01-28 13:44:02.814752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb8ab4948953'
down_revision: Union[str, None] = 'f1f66de3266e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_query_sentiment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('initial_query_sentiment_explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('conversation_sentiment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('conversation_sentiment_explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.drop_column('conversation_sentiment_explanation')
        batch_op.drop_column('conversation_sentiment')
        batch_op.drop_column('initial_query_sentiment_explanation')
        batch_op.drop_column('initial_query_sentiment')
    # ### end Alembic commands ###
