"""bfa-154 add is_notified to user model

Revision ID: cf270df9db6a
Revises: 81c4dcbea409
Create Date: 2025-06-07 08:38:10.610283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cf270df9db6a'
down_revision: Union[str, None] = '81c4dcbea409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receive_notifications', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('receive_notifications')

    # ### end Alembic commands ###
