"""add secret keys to accounts

Revision ID: d72d84cc6c75
Revises: bb8ab4948953
Create Date: 2026-03-27 08:55:57.523984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd72d84cc6c75'
down_revision: Union[str, None] = 'bb8ab4948953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_us_secret_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('opt_in_webhook_secret_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('opt_in_webhook_secret_key')
        batch_op.drop_column('contact_us_secret_key')

    # ### end Alembic commands ###
