"""Add chunk_size and chunk_overlap to Account model

Revision ID: d7a1195312b7
Revises: 207693e32403
Create Date: 2024-10-03 10:54:04.672600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd7a1195312b7'
down_revision: Union[str, None] = '207693e32403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('chunk_size', sa.Integer(), nullable=True))
    op.add_column('account', sa.Column('chunk_overlap', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'chunk_overlap')
    op.drop_column('account', 'chunk_size')
    # ### end Alembic commands ###
