"""Add product model

Revision ID: f4e4010db60a
Revises: a017d60d9377
Create Date: 2025-09-24 08:32:42.879000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f4e4010db60a'
down_revision: Union[str, None] = 'a017d60d9377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userproduct',
    sa.Column('account_unique_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_sale_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('who_is_this_for', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['account_unique_id'], ['account.account_unique_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userproduct')
    # ### end Alembic commands ###
